- name: Install Apache linux server
  hosts: HIC034141.dc.honeywell.com
  become: yes
  become_user: root
  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: installed
  - name: Restart apache
    service:
      name: httpd
      state: restarted
