- hosts: HIC034141.dc.honeywell.com
  remote_user: root
  become: yes
  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: installed
  - name: Restart apache
    service:
      name: httpd
      state: restarted
